"""Initial migration.

Revision ID: f5d6aeeb9441
Revises: 
Create Date: 2022-02-26 23:00:22.071508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d6aeeb9441'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    product_table = op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sku')
    )
    user_table = op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    
    op.bulk_insert(product_table, [
            {'sku': 'TS-001', 'name': 'T-Shirt', 'price': 10.99, 'brand': 'Zebra'},
            {'sku': 'TS-002', 'name': 'Shoes', 'price': 13.99, 'brand': 'Leonisa'},
            {'sku': 'TS-003', 'name': 'Socks', 'price': 15.99, 'brand': 'Nike'},
            {'sku': 'TS-004', 'name': 'Ties', 'price': 16.99, 'brand': 'Dolce & Gabbana'},
            {'sku': 'TS-005', 'name': 'Pants', 'price': 17.99, 'brand': 'Zara'},
        ]
    )

    op.bulk_insert(user_table, [
        {'username': 'admin', 'email': 'admin@admin.com', 'password': 'pbkdf2:sha256:260000$JDcEoj5z6k0zIEXL$dda5d5a809894ab23cb617f4b66b03164456252dbed763220d50b7806a9225a9', 'isAdmin': True},
        {'username': 'user', 'email': 'user@user.com', 'password': 'pbkdf2:sha256:260000$vnJcvOGzpVAsiOQz$a56a5e2eaaf0bb54a4d786dc5d227080d65bf69c2e182c04ec61f5fe659d4694', 'isAdmin': False},
    ])        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###
